### ISSUE TITLE
progressView must be put inside a LinearLayout!

### ISSUE THREAD

**Issue by mehranabi** [gotev/android-speech#13]
Hello,

Why we must put SpeechProgressView inside a LinearLayout ?
I put it in a **FrameLayout**  but I got error!

**Comment by gotev** [comment]
Because of how the view is implemented. I invite you to look at it, and if you have ideas and time to improve it and make it work outside a LinearLayout, I will be glad to accept your PR!

**Comment by mehranabi** [comment]
OK, I will do.
Thanks

**Comment by gotev** [comment]
Closing this due to lack of contributions so far

**Comment by mehranabi** [comment]
Hello @gotev , I've forgotten this issue because I got busy with my projects, And I just got an email about closing this issue...
Actually, It's a while that I'm not working on native Android projects...
I think closing this issue is good for now because I was the only participant of it :)
