### ISSUE TITLE
Unable to set StopListeningAfterInactivity

### ISSUE THREAD

**Issue by afomic** [gotev/android-speech#18]
whatever value I set  for the is method it doesn't seem to make any effect

**Comment by gotev** [comment]
Please provide more context and steps to reproduce

**Comment by afomic** [comment]
public class App extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        FirebaseDatabase.getInstance().setPersistenceEnabled(true);
        Speech.init(this, getPackageName());
        Speech.getInstance().setStopListeningAfterInactivity(10000)
                .setGetPartialResults(false);

        Logger.setLogLevel(Logger.LogLevel.DEBUG);
    }
}
this how am setting the  stopListeningAfterInactivity, but if i stop talking for like 2s, the app makes a sound and stop listening  for more input

**Comment by gotev** [comment]
This is standard behaviour of the underlying Android Speech API. This library is a simple wrapper.
