### ISSUE TITLE
Minimum API version

### ISSUE THREAD

**Issue by dreich** [gotev/android-speech#20]
Please tell what is the minimal Android API version for you library?
For example, on API 10 Speech.init() gives java.lang.NoClassDefFoundError: net.gotev.speech.TtsProgressListener.

I've got into trouble with the production version of my app for a user with 2.3.3 version of Android.

**Comment by Ruthvik47** [comment]
I look I'm k I'I'm ki ki I'
Kik Im k ki m mm kmk I'm mi

K ki
I'mkmom k

**Comment by Ruthvik47** [comment]
I'm
Mom I'm m


I look mk
I'm i ki un

**Comment by Ruthvik47** [comment]
I m k mom mom

**Comment by Ruthvik47** [comment]
K lol

**Comment by Ruthvik47** [comment]
Kkm

**Comment by gotev** [comment]
@dreich 16. You can find it also here: https://github.com/gotev/android-speech/blob/master/speech/build.gradle

@Ruthvik47 has probably fallen asleep on his keyboard :smiley: Have a nice rest!

**Comment by Ruthvik47** [comment]
Can we use this as wake up word like google has okay Google ?
