### ISSUE TITLE
API or URL on Private connection

### ISSUE THREAD

**Issue by jjimenez0611** [gotev/android-speech#21]
Hi 

I have a private connection in my company, and some urls are blocked. I really need to know which API or URL use this library to unlock in my private connection. 

Best Regards

**Comment by jjimenez0611** [comment]
Does your library use https://speech.googleapis.com??

**Comment by gotev** [comment]
This library simply wraps the Android native speech recognizer and I don't
have that information. With a proxy you will see the contacted URLs

Il giovedì 12 aprile 2018, Jose Jimenez <notifications@github.com> ha
scritto:
