### ISSUE TITLE
Pronunciation of words is inconsistent

### ISSUE THREAD

**Issue by LAHomieJob** [gotev/android-speech#25]
I have a problem with sequential using of .say method. For example I wrote the follow operators:
```
Speech.getInstance().say("First Word”);
Speech.getInstance().say("Second Word”);
Speech.getInstance().say("Third Word”);
```
From this code I will hear only the last "Third word" phrase, but others will be skipped. How can I make to speak all phrases in sequel manner, when the next operator is called only after previous have finished speaking

To solve my problem I tried to use ADD_QUEUE mode but it doesn't work like I want. With this mode all words will be simply pushing into the queue without waiting for the end of speaking.

**Comment by gotev** [comment]
For the moment you can use the Text To Speech callback and add every new thing inside that. I agree it's not elegant. Maybe an Rx interface can make thing prettier.
