### ISSUE TITLE
Continuous recognition

### ISSUE THREAD

**Issue by jaag12** [gotev/android-speech#27]
Is a continuous recognition possible with this library?

**Comment by gotev** [comment]
No, you need to use Google Cloud Speech

**Comment by Anshul1507** [comment]
Yes, continuous recognition possible.

you can add this in onSpeechResult method after setting text,

           Speech.getInstance().stopTextToSpeech();

                Handler handler = new Handler();
                handler.postDelayed(new Runnable() {
                    @Override
                    public void run() {
                        try {
                            Speech.getInstance().startListening(progress, MainActivity.this);
                        } catch (SpeechRecognitionNotAvailable speechRecognitionNotAvailable) {
                            speechRecognitionNotAvailable.printStackTrace();
                        } catch (GoogleVoiceTypingDisabledException e) {
                            e.printStackTrace();
                        }
                    }
                }, 100);
