### ISSUE TITLE
Library used for speech recognition?

### ISSUE THREAD

**Issue by ChrisTomAlx** [gotev/android-speech#28]
Hey,

I have two quick questions.
1.  Does this use googles speech recognition api ? 
2.  Does it work offline? 

Thanks for the good work. 👍

**Comment by gotev** [comment]
This library is only a helper wrapper of https://developer.android.com/reference/android/speech/package-summary 

Underneath it uses Cloud Speech API. Offline capability depends on device configuration. More on https://stackoverflow.com/questions/17616994/offline-speech-recognition-in-android-jellybean

**Comment by ChrisTomAlx** [comment]
Thank you for your quick response!
