### ISSUE TITLE
Issue in Offline mode

### ISSUE THREAD

**Issue by Anshul1507** [gotev/android-speech#38]
Didn't recognizing properly in offline mode?

Is there any separate method for offline?
PS: Speech.getInstance().setPreferOffline(true); is not working.

**Comment by gotev** [comment]
It vastly depends on the vendor, language availability (not all languages are available offline), android version and Google App version installed.

**Comment by Anshul1507** [comment]
I tried English Language and it is not recognized. Android Version is 9.0 and 6.0.

**Comment by gotev** [comment]
AFAIK the only setting available in the public APIs is whether or not offline mode should be preferred (that's how Speech does it), but I have found no way to actually tell the system to download selected languages programmatically, which is maybe what causes your issues. 

On my stock Moto X4 Android 9, just by setting offline it works. Do you have stock Android?

Take a look here: https://stackoverflow.com/questions/31562229/offline-speech-recognition-in-android

Do you have proposals or other suggestions?

**Comment by Anshul1507** [comment]
Yep, my Android 9.0 device is stock android but offline recogn. is somewhat not perfect. Later, I found another [library](https://github.com/alphacep/vosk-api) which also works in offline mode, here is [demo](https://github.com/alphacep/vosk-android-demo) of that.

**Comment by gotev** [comment]
Thanks for sharing! It's interesting and it's using [Kaldi](https://link.medium.com/ZXfNw6q9K7) open source speech recognition engine. 

It's completely different from what this library is using, which is Android bundled-in SpeechRecognizer and TextToSpeech.

**Comment by Anshul1507** [comment]
Agreed, totally different. that kaldi is whole model based on different language.
