### ISSUE TITLE
Continuous Speech Recognition 

### ISSUE THREAD

**Issue by Anshul1507** [gotev/android-speech#39]
It can be possible with your library at a minimal interval of 100ms. 

PS: I make a [PR](https://github.com/gotev/android-speech/pull/37) related to this

**Comment by gotev** [comment]
Seen #37 but it's a workaround which can cause activity lifecycle leaks. You'll almost always hear the bundled in beep at regular intervals, don't you? Google Voice Search, which is the system service used by this library, isn't meant for continuous listening.

**Comment by Anshul1507** [comment]
I lowered the device audio at the time of create activity and back to normal (default) when user press back, in this way i remove that regular beep.

**Comment by gotev** [comment]
Oh wow, that's many workarounds in a row. Are you using this in any production app?

**Comment by Anshul1507** [comment]
Not in any production app, but i make one sample paragraph reading app with your library. [Code Link](https://github.com/Anshul1507/Realtime-Speech-to-Text).
