### ISSUE TITLE
Synthesis request paramter streamType containst value  with invalid type

### ISSUE THREAD

**Issue by zhou880220** [gotev/android-speech#48]
code: Speech.getInstance().say("hello")
log: Synthesis request paramter streamType containst value  with invalid type. Should be an Integer or a Long

Please help me solve this problem.

**Comment by yuripourre** [comment]
Hello @zhou880220, your log has a typo: `containst` could you please post the exact log you are getting?

**Comment by zhou880220** [comment]
> could you please post the exact log you are getting?

03-23 09:28:23.795 4713-4713/com.tianyi.story I/TtsActivity: onSpeakClick: start
03-23 09:28:23.795 4713-4713/com.tianyi.story W/TextToSpeech: Synthesis request paramter streamType containst value  with invalid type. Should be an Integer or a Long
03-23 09:28:23.805 4713-4713/com.tianyi.story I/TtsActivity: onSpeakClick: end

**Comment by gotev** [comment]
@zhou880220 A bunch of questions to understand the issue and have some meaningful data:
- Which library version are you using?
- On which Android version does it happen and from which vendor?
- Which language do you have on the device and which language are you trying to use for TTS?
- Do you have a demo app which replicates this problem (or at least an executable snippet)?
- Does it happen on a single device or on many devices (specify which)?
- Have you tried the Speech Demo App on the same device on which you are getting this error? What are the outcomes?

**Comment by zhou880220** [comment]
> @zhou880220 A bunch of questions to understand the issue and have some meaningful data:
> 
> * Which library version are you using?
> * On which Android version does it happen and from which vendor?
> * Which language do you have on the device and which language are you trying to use for TTS?
> * Do you have a demo app which replicates this problem (or at least an executable snippet)?
> * Does it happen on a single device or on many devices (specify which)?
> * Have you tried the Speech Demo App on the same device on which you are getting this error? What are the outcomes?


my test phone sdk is 28, phone  language is chinese and tts is useful;
I try  [https://github.com/mapzen/speakerbox.git](url)  can running .

**Comment by gotev** [comment]
@zhou880220 ok! Have you tried the Speech Demo App on the same device on which you are getting this error? What are the outcomes?

**Comment by zhou880220** [comment]
> @zhou880220 ok! Have you tried the Speech Demo App on the same device on which you are getting this error? What are the outcomes?

This is probably a Chinese phone, some flaws in Google TTS support, I tried other brands as well.

**Comment by gotev** [comment]
From the report got so far, the problem doesn't seem something related to the library, but more about Google TTS support for Chinese and some device specific issues. The library is simply a wrapper of android native capabilities. No action to take here.
