### ISSUE TITLE
Speech Recognition doesnt work

### ISSUE THREAD

**Issue by n-droidev** [gotev/android-speech#49]
Speech recognition doesnt work.. It calls onSpeechResult method immediately after onStartOfSpeech method.

**Comment by n-droidev** [comment]
Library cant recognize speech offline.

**Comment by gotev** [comment]
More details?

**Comment by n-droidev** [comment]
I didnt know what is the problem.. But I realized that Library cant recognize speech with setPreferOffline method.. Briefly if I call setPreferOffline(true) method, Library cant recognize speech. Stops immediately..

**Comment by n-droidev** [comment]
And I have another question.. How Can I make library recognize speech in other languages. It recognize only english. Even after I set Speech.getInstance(this).setLocale(Locale.Something).

**Comment by gotev** [comment]
The library is a wrapper over Google Voice Search. If that doesn't work it means offline voice settings on the device are not enabled and the language you tried is not downloaded. You can try the demo app and I think you will get the same result. This is unfortunately out of the scope of the library and you have to look at Google voice Search native interface. As far as I know there's no way to force or request a language to be downloaded for offline usage.

**Comment by n-droidev** [comment]
Ok.. Thank you very much.
