### ISSUE TITLE
Text to speech not working when device screen is off

### ISSUE THREAD

**Issue by SenghaniMaulik** [gotev/android-speech#52]
Thanks for this good lib.

I am developing one app in which i **want to play text to speech on foreground service** .
its working fine when device screen is ON but **its not working sometime when device screen is OFF**,
can you please suggest possible solution and cause of this issue.

Thanks

**Comment by gotev** [comment]
Hi! Never tried such a scenario. The lib simply wraps system's TTS engine. At the moment I'm not aware if it should work also in the background.

It would be great if you make a PR on the demo app with this kind of implementation.
