### ISSUE TITLE
Saving recording as mp3

### ISSUE THREAD

**Issue by kalasaceo** [gotev/android-speech#53]
How can we save the speech from text to mkp3 or other audio format.

**Comment by gotev** [comment]
Not supported by the library, but I saw the Android native [TextToSpeech](https://developer.android.com/reference/android/speech/tts/TextToSpeech#synthesizeToFile(java.lang.CharSequence,%20android.os.Bundle,%20java.io.File,%20java.lang.String)) class has a method which seems to do what you need
