### ISSUE TITLE
Speech recognition stops after first result

### ISSUE THREAD

**Issue by PeterStaranchuk** [gotev/android-speech#6]
Hello. How can I cycle recognition?
I mean - listen all time

**Comment by gotev** [comment]
Listening all the time until you explicitly stop it is not possibile. The idle timeout can be set, but nothing more. To add continuous listening you must use Google Cloud Speech API gRPC

**Comment by PeterStaranchuk** [comment]
thanks)

**Comment by gotev** [comment]
It's a limitation posed by the android speech recognition APIs
