### ISSUE TITLE
Continuous speech recognition

### ISSUE THREAD

**Issue by Jiks19** [gotev/android-speech#62]
How to continuous speech to text without google dialog?

Is it possible ?
If yes please share code>

Thanks

**Comment by gotev** [comment]
Not possible. This wraps Google Voice Search system service, which do not support this. You have to use another engine.

**Comment by Jiks19** [comment]
@gotev 
Thank to replay.

Can you help me with another solution?
Can you provide another solution source code link?
OR
Some suggestion? 

Thanks

**Comment by gotev** [comment]
Nothing that I'm aware of

**Comment by Jiks19** [comment]
Okay 
Thanks @gotev
