### ISSUE TITLE
Canceling SpeechRecognition

### ISSUE THREAD

**Issue by Hokyjack** [gotev/android-speech#65]
Hi, is there any way to cancel the SpeechRecognition after it starts recording,
so I don't have to wait until it stops because of silence.
I can see there is a method cancel() in BaseSpeechRecognitionEngine,
but there is no interface to access it. Is there any workouround around it?
Thanks!

**Comment by rehmanjameel** [comment]
Yes, you can do it by using stopListening() method.

``` java
linearLayout.setOnClickListener(view -> {
            Speech.getInstance().stopListening();
            button.setVisibility(View.VISIBLE);
            linearLayout.setVisibility(View.GONE);
        });
```

linearlayout is the layout of progress view by clicking on layout you can stopListening.
I hope this will be help full for you.
