### ISSUE TITLE
 getSupportedTextToSpeechVoices() returns null

### ISSUE THREAD

**Issue by ChristophyBarth** [gotev/android-speech#67]
.

**Comment by yuripourre** [comment]
@ChristophyBarth did you find the problem? How did you solve it?

**Comment by ChristophyBarth** [comment]
> @ChristophyBarth did you find the problem? How did you solve it?

The Speech code called after init was too close. So you have to take init to your launcher activity, and before you get to the activity where you need to use it, it would have successfully been initialized.

**Comment by yuripourre** [comment]
Thank you for the explanation it might be useful for other people!

**Comment by gotev** [comment]
@ChristophyBarth I can confirm this behavior having experienced it in the past. The approach you're suggesting is the best one among the ones I've also tried. Thank you!
