### ISSUE TITLE
Language selection

### ISSUE THREAD

**Issue by rehmanjameel** [gotev/android-speech#69]
When i select a language other than English and close the app after reopen the app language has changed to English as default.

Is there any way to save the other selected language instead of default US-English?

**Comment by yuripourre** [comment]
You will need to store the same way you do for any other app. You can use shared preferences.

**Comment by gotev** [comment]
The speech engine uses device's default language, so it's going to always use that when you start it up. To use a different language, follow @yuripourre suggestion

**Comment by rehmanjameel** [comment]
> You will need to store the same way you do for any other app. You can use shared preference
Yes, I stored the chosen language in the shared preferences, and it is now functioning. Thanks for you suggestion, It's helpful.
