### ISSUE TITLE
Tracking if user speaking or finished

### ISSUE THREAD

**Issue by xml2208** [gotev/android-speech#70]
hi,
Is there any way to track the user speaking?/
I need to know the whether he/she finished speaking.

**Comment by gotev** [comment]
Yes, by passing a [SpeechProgressView when you start listening](https://github.com/gotev/android-speech?tab=readme-ov-file#display-progress-animation). The ProgressView's [onEndOfSpeech](https://github.com/gotev/android-speech/blob/1352d77ecdb757164f83e51797827fb445d5be25/speech/src/main/java/net/gotev/speech/ui/SpeechProgressView.java#L277) method will be called by the speech engine.

**Comment by xml2208** [comment]
Thanks, @gotev but how to use BaseSpeechRecognitionEngine?

**Comment by gotev** [comment]
That's only meant to be subclassed to support more speech engines. For your use case simply invoke this method to start listening: https://github.com/gotev/android-speech/blob/1352d77ecdb757164f83e51797827fb445d5be25/speech/src/main/java/net/gotev/speech/Speech.java#L145 passing the SpeechProgressView. You can subclass it if you need further customization.

**Comment by xml2208** [comment]
Thank you!
