### ISSUE TITLE
Record speech to text voice

### ISSUE THREAD

**Issue by neronguyen** [gotev/android-speech#71]
Hi, did you find a solution to record the speech to text voice with MediaRecorder ?. Seems it is proritiezed when enabled and take over the speech voice so speech to text function no longer work.

**Comment by gotev** [comment]
Haven't made such experiments yet. It's entirely handled by the system, however it makes sense to disable the voice search feature if a recording is already happening.

**Comment by neronguyen** [comment]
yeah, I still trying to find a way to make speech to text and record work simultaneously but seems no hope; all suggest using api that supports voice stream like google speech api but that costs much

**Comment by gotev** [comment]
@neronguyenvn the suggestion you got is correct and unless you use some open source project you could find, that's the way and it costs

**Comment by neronguyen** [comment]
thankss
